version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: vernette/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/foodgram/media/
    depends_on:
      - db

  frontend:
    container_name: foodgram-frontend
    image: vernette/foodgram_frontend
    command: sh -c "cp -r /app/build/. /frontend_static"
    volumes:
      - static_volume:/frontend_static

  gateway:
    container_name: foodgram-proxy
    image: vernette/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static_volume:/static
      - static_volume:/usr/share/nginx/html
      - ./docs:/usr/share/nginx/html/api/docs
    volumes_from:
      - backend:ro